# Generated by Django 6.0.5 on 2026-06-25 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_status_pay"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status_pay",
            options={
                "verbose_name": "Статус оплаты",
                "verbose_name_plural": "Статусы оплаты",
            },
        ),
        migrations.AddField(
            model_name="status_pay",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="status_pay",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
