# Generated by Django 6.0.5 on 2026-06-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_initial"),
    ]

    operations = []
