# Generated by Django 6.0.5 on 2026-06-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_auto_20260618_2344"),
    ]

    operations = []
