# Generated by Django 6.0.5 on 2026-06-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_auto_20260618_2348"),
    ]

    operations = []
