# Generated by Django 6.0.5 on 2026-06-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_auto_20260618_2354"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="title",
            new_name="name",
        ),
    ]
