# Generated by Django 6.0.5 on 2026-06-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_rename_title_lesson_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["id"]},
        ),
    ]
