# Generated by Django 6.0.5 on 2026-06-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_alter_course_options_alter_lesson_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Цена"
            ),
        ),
    ]
