# Generated by Django 6.0.5 on 2026-07-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_course_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
