# Generated by Django 6.0.5 on 2026-08-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_alter_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
